In [1]:
from hw2fintools import gurufocus as gf
import os
from dotenv import load_dotenv
import pandas as pd
import re
import numpy as np


load_dotenv()
path_stockdata = os.path.join(os.environ.get('judgement_day'), 'StockData')
date_pattern = r"(\d\d\d\d-\d\d-\d\d)--"

ticker_list = os.listdir(path_stockdata)

In [2]:
for item in ticker_list:
    loc = 0
    if item.startswith('._'):
        ticker_list.remove(item)

ticker_list.sort()

process_df = pd.DataFrame(ticker_list, columns=['Ticker'])
process_df

   Ticker
0    AAPL
1    ABBV
2     ADM
3     ADP
4     AMD
..    ...
88      V
89     VZ
90    WMT
91    XOM
92    ZTS

[93 rows x 1 columns]

In [3]:
process_df['DivFile'] = ''
process_df['DivData'] = False
process_df['PriceFile'] = ''
process_df['PriceData'] = False
process_df['DateMatch'] = ''

process_df

   Ticker DivFile  DivData PriceFile  PriceData DateMatch
0    AAPL            False                False
1    ABBV            False                False
2     ADM            False                False
3     ADP            False                False
4     AMD            False                False
..    ...     ...      ...       ...        ...       ...
88      V            False                False
89     VZ            False                False
90    WMT            False                False
91    XOM            False                False
92    ZTS            False                False

[93 rows x 6 columns]

In [4]:
for index, row in process_df.iterrows():
    path_ticker = os.path.join(path_stockdata, row['Ticker'])
    div_list = []
    price_list = []

    for item in os.listdir(path_ticker):
        if 'gf-raw-dividend_history' in item and item.endswith('.csv') and not item.startswith('._'):
            div_list.append(item)
        elif 'gf-raw-price_history' in item and item.endswith('.csv') and not item.startswith('._'):
            price_list.append(item)

    div_list_sorted = sorted(div_list, reverse=True)
    div_current = div_list_sorted[0]
    process_df.loc[index, 'DivFile'] = div_current

    price_list_sorted = sorted(price_list, reverse=True)
    price_current = price_list_sorted[0]
    process_df.loc[index, 'PriceFile'] = price_current

    div_df = pd.read_csv(os.path.join(path_ticker, div_current))

    div_len = len(div_df)

    if div_len <= 20:
        process_df.loc[index, 'DivData'] = False
    else:
        process_df.loc[index, 'DivData'] = True

    price_df = pd.read_csv(os.path.join(path_ticker, price_current))

    if price_df.empty:
        process_df.loc[index, 'PriceData'] = False
    else:
        process_df.loc[index, 'PriceData'] = True

    div_date = re.search(date_pattern, div_current)
    price_date = re.search(date_pattern, price_current)

    div_match = div_date.group(1)
    price_match = price_date.group(1)

    if div_match == price_match:
        process_df.loc[index, 'DateMatch'] = True
    else:
        process_df.loc[index, 'DateMatch'] = False

In [5]:
process_df

,Ticker,DivFile,DivData,PriceFile,PriceData,DateMatch
0,AAPL,2025-12-01--AAPL--gf-raw-dividend_history.csv,True,2025-12-01--AAPL--gf-raw-price_history.csv,True,True
1,ABBV,2025-12-01--ABBV--gf-raw-dividend_history.csv,True,2025-12-01--ABBV--gf-raw-price_history.csv,True,True
2,ADM,2025-12-01--ADM--gf-raw-dividend_history.csv,True,2025-12-01--ADM--gf-raw-price_history.csv,True,True
3,ADP,2025-12-01--ADP--gf-raw-dividend_history.csv,True,2025-12-01--ADP--gf-raw-price_history.csv,True,True
4,AMD,2025-12-09--AMD--gf-raw-dividend_history.csv,False,2025-12-09--AMD--gf-raw-price_history.csv,True,True
...,...,...,...,...,...,...
88,V,2025-12-01--V--gf-raw-dividend_history.csv,True,2025-12-01--V--gf-raw-price_history.csv,True,True
89,VZ,2025-12-01--VZ--gf-raw-dividend_history.csv,True,2025-12-01--VZ--gf-raw-price_history.csv,True,True
90,WMT,2025-12-01--WMT--gf-raw-dividend_history.csv,True,2025-12-01--WMT--gf-raw-price_history.csv,True,True
91,XOM,2025-12-01--XOM--gf-raw-dividend_history.csv,True,2025-12-01--XOM--gf-raw-price_history.csv,True,True
92,ZTS,2025-12-01--ZTS--gf-raw-dividend_history.csv,True,2025-12-01--ZTS--gf-raw-price_history.csv,True,True

In [6]:
mask = (process_df['DivData'] == True) & (process_df['PriceData'] == True) & (process_df['DateMatch'] == True)
auto_run_df = process_df[mask].copy()
auto_run_df

,Ticker,DivFile,DivData,PriceFile,PriceData,DateMatch
0,AAPL,2025-12-01--AAPL--gf-raw-dividend_history.csv,True,2025-12-01--AAPL--gf-raw-price_history.csv,True,True
1,ABBV,2025-12-01--ABBV--gf-raw-dividend_history.csv,True,2025-12-01--ABBV--gf-raw-price_history.csv,True,True
2,ADM,2025-12-01--ADM--gf-raw-dividend_history.csv,True,2025-12-01--ADM--gf-raw-price_history.csv,True,True
3,ADP,2025-12-01--ADP--gf-raw-dividend_history.csv,True,2025-12-01--ADP--gf-raw-price_history.csv,True,True
5,AMT,2025-12-01--AMT--gf-raw-dividend_history.csv,True,2025-12-01--AMT--gf-raw-price_history.csv,True,True
...,...,...,...,...,...,...
88,V,2025-12-01--V--gf-raw-dividend_history.csv,True,2025-12-01--V--gf-raw-price_history.csv,True,True
89,VZ,2025-12-01--VZ--gf-raw-dividend_history.csv,True,2025-12-01--VZ--gf-raw-price_history.csv,True,True
90,WMT,2025-12-01--WMT--gf-raw-dividend_history.csv,True,2025-12-01--WMT--gf-raw-price_history.csv,True,True
91,XOM,2025-12-01--XOM--gf-raw-dividend_history.csv,True,2025-12-01--XOM--gf-raw-price_history.csv,True,True
92,ZTS,2025-12-01--ZTS--gf-raw-dividend_history.csv,True,2025-12-01--ZTS--gf-raw-price_history.csv,True,True

In [7]:
for index, row in auto_run_df.iterrows():
    path_ticker = os.path.join(path_stockdata, row['Ticker'])
    div_path = os.path.join(path_ticker, row['DivFile'])
    price_path = os.path.join(path_ticker, row['PriceFile'])

    print(row['Ticker'] + '--Start')

    div_df0 = gf.div_hist_s1v1(div_path)
    price_df0 = gf.price_hist_s2v1(price_path)

    div_df1 = div_df0.loc[div_df0['DivType'] == 'regular']
    div_df1 = div_df1.drop(columns=['DivRecordDate', 'DivDeclareDate', 'DivPayDate'])
    div_df1 = div_df1.rename(columns={'ExDivDate': 'Date'})

    merged_df0 = pd.merge(price_df0, div_df1, on='Date', how='left')
    merged_df0['DivAmount'] = merged_df0['DivAmount'].fillna(0)
    merged_df0['DivFrequency'] = merged_df0['DivFrequency'].fillna(div_df1.iloc[0]['DivFrequency'])
    merged_df0['DivType'] = merged_df0['DivType'].fillna(div_df1.iloc[0]['DivType'])
    merged_df0['DivPayDeclared'] = merged_df0['DivAmount'].fillna(0)

    div_var = 0

    for index1, row1 in merged_df0.iterrows():
        if row1['DivAmount'] > 0:
            div_var = row1['DivAmount']

        else:
            merged_df0.at[index1, 'DivAmount'] = div_var

    merged_df0['FwdDiv'] = merged_df0['DivFrequency'] * merged_df0['DivAmount']
    merged_df0['FwdDivYield'] = merged_df0['FwdDiv'] / merged_df0['PricePerShare']

    aggr_df0 = merged_df0
    aggr_df0 = aggr_df0.set_index('Date')
    aggr_df1 = aggr_df0.groupby(aggr_df0.index.year).agg(
        SharePriceMin=pd.NamedAgg(column='PricePerShare', aggfunc='min'),
        SharePriceMax=pd.NamedAgg(column='PricePerShare', aggfunc='max'),
        SharePriceMean=pd.NamedAgg(column='PricePerShare', aggfunc='mean'),
        SharePriceMedian=pd.NamedAgg(column='PricePerShare', aggfunc='median'),
        DivYieldMin=pd.NamedAgg(column='FwdDivYield', aggfunc='min'),
        DivYieldMax=pd.NamedAgg(column='FwdDivYield', aggfunc='max'),
        DivYieldMean=pd.NamedAgg(column='FwdDivYield', aggfunc='mean'),
        DivYieldMedian=pd.NamedAgg(column='FwdDivYield', aggfunc='median'),
        DividendPaidTotalCy=pd.NamedAgg('DivPayDeclared', aggfunc='sum')
    )

    merged_df0.to_csv(os.path.join(path_ticker, row['Ticker'].upper() + '--DivPrice_History--s3v1.csv'))
    aggr_df1.to_csv(os.path.join(path_ticker, row['Ticker'].upper() + '--Aggregate_Cy_DivPrice_History--s4v1.csv'))

    print(row['Ticker'] + '--Completed')

AAPL--Start
ABBV--Start
ADM--Start
ADP--Start
AMT--Start
AOS--Start
ASML--Start
AVGO--Start
AWK--Start
BBY--Start
BF.A--Start
BLK--Start
BMY--Start
CAT--Start
CCI--Start
CL--Start
CLX--Start
CMCSA--Start
CNI--Start
COST--Start
CPB--Start
CVS--Start
CVX--Start
D--Start
DE--Start
DEO--Start
DLR--Start
DOW--Start
DUK--Start
ED--Start
EMN--Start
EOG--Start
EQIX--Start
FAST--Start
FDX--Start
FLO--Start
GD--Start
GIS--Start
HD--Start
HRL--Start
HSY--Start
INTC--Start
INTU--Start
IRM--Start
JNJ--Start
KMB--Start
KO--Start
LLY--Start
LMT--Start
LOW--Start
LRCX--Start
LYB--Start
MAN--Start
MCD--Start
MDLZ--Start
MDT--Start
MKC.V--Start
MMM--Start
MO--Start
MRK--Start
MSFT--Start
NKE--Start
NOC--Start
NVDA--Start
O--Start
PEP--Start
PFE--Start
QCOM--Start
SCHW--Start
SHW--Start
SJM--Start
SNA--Start
SO--Start
SPG--Start
SPGI--Start
T--Start
TGT--Start
TROW--Start
TSM--Start
TSN--Start
TXN--Start
UNH--Start
UNP--Start
UPS--Start
V--Start
VZ--Start
WMT--Start
XOM--Start
ZTS--Start